-- Create test listings near zip code 18054 (Bethlehem, PA area)
-- These will appear in the admin pending submissions for testing

-- Insert 3 test venues
INSERT INTO public.listings (
  id,
  type,
  status,
  title,
  description,
  category,
  venue_name,
  address,
  city,
  state,
  zip,
  latitude,
  longitude,
  email,
  phone,
  website,
  sensory_features,
  crowd_level,
  accessibility_notes,
  images,
  organizer_email,
  source,
  submitted_at,
  created_at,
  updated_at
) VALUES
(
  gen_random_uuid(),
  'venue',
  'pending',
  'Quiet Corner Cafe & Bookshop',
  'A cozy neighborhood cafe with a dedicated quiet reading nook. Features low lighting, soft background music at low volumes, and comfortable seating. Perfect for individuals seeking a calm environment to read, work, or enjoy a peaceful coffee break. We maintain strict noise policies during business hours.',
  'cafe',
  'Quiet Corner Cafe',
  '1234 Main Street',
  'Bethlehem',
  'PA',
  '18018',
  40.6259,
  -75.3705,
  'info@quietcornercafe.com',
  '(610) 555-0123',
  'https://quietcornercafe.com',
  ARRAY['Low lighting', 'Quiet zones available', 'Minimal background noise', 'Comfortable seating'],
  'Low',
  'Wheelchair accessible entrance and restroom. Service animals welcome. Noise-canceling headphones available upon request.',
  ARRAY['/placeholder.svg?height=400&width=600'],
  'owner@quietcornercafe.com',
  'community',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '2 days'
),
(
  gen_random_uuid(),
  'venue',
  'pending',
  'Sensory-Friendly Arts Studio',
  'A welcoming art studio designed with sensory considerations in mind. We offer painting, pottery, and craft classes in a controlled environment with adjustable lighting, minimal auditory distractions, and flexible class sizes. All materials are hypoallergenic and fragrance-free.',
  'indoor',
  'Bethlehem Art Haven',
  '567 Broad Street',
  'Allentown',
  'PA',
  '18102',
  40.6023,
  -75.4714,
  'hello@arthavenpa.com',
  '(484) 555-0234',
  'https://arthavenpa.com',
  ARRAY['Adjustable lighting', 'Quiet environment', 'Small group sizes', 'Fragrance-free materials'],
  'Low',
  'Fully accessible studio with wide aisles. Fidget tools and weighted lap pads available. Visual schedules provided for all activities.',
  ARRAY['/placeholder.svg?height=400&width=600'],
  'director@arthavenpa.com',
  'community',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day'
),
(
  gen_random_uuid(),
  'venue',
  'pending',
  'Peaceful Garden Library',
  'A unique library experience featuring indoor and outdoor quiet spaces surrounded by gardens. Collections include large-print books, audiobooks, and sensory-friendly reading materials. Private study rooms available with advance booking.',
  'library',
  'East Penn Community Library',
  '890 Library Lane',
  'Emmaus',
  'PA',
  '18049',
  40.5398,
  -75.4963,
  'contact@eastpennlibrary.org',
  '(610) 555-0345',
  'https://eastpennlibrary.org',
  ARRAY['Very quiet environment', 'Natural lighting', 'Outdoor seating available', 'Private study rooms'],
  'Very Low',
  'ADA compliant throughout. Assistive listening devices available at circulation desk. Braille materials in collection.',
  ARRAY['/placeholder.svg?height=400&width=600'],
  'librarian@eastpennlibrary.org',
  'community',
  NOW() - INTERVAL '3 hours',
  NOW() - INTERVAL '3 hours',
  NOW() - INTERVAL '3 hours'
),
(
  gen_random_uuid(),
  'event',
  'pending',
  'Morning Meditation in the Park',
  'Join us for a gentle guided meditation session in a peaceful outdoor setting. This sensory-friendly event features optional noise-canceling equipment, visual cues for all instructions, and a quiet, supportive atmosphere. All experience levels welcome. Please bring your own mat or blanket.',
  'outdoor',
  'Sand Island Park',
  '200 River Street',
  'Bethlehem',
  'PA',
  '18015',
  40.6098,
  -75.3532,
  'events@bethlehemwellness.com',
  '(610) 555-0456',
  'https://bethlehemwellness.com/events',
  ARRAY['Outdoor setting', 'Quiet activity', 'Visual instruction provided', 'Flexible participation'],
  'Very Low',
  'Accessible parking available. Event held on flat, paved surface. ASL interpreter available upon request with 48hr notice.',
  ARRAY['/placeholder.svg?height=400&width=600'],
  'coordinator@bethlehemwellness.com',
  'community',
  NOW() - INTERVAL '5 hours',
  NOW() - INTERVAL '5 hours',
  NOW() - INTERVAL '5 hours'
),
(
  gen_random_uuid(),
  'event',
  'pending',
  'Sensory-Friendly Movie Matinee',
  'Experience cinema in a welcoming, understanding environment. Reduced sound levels, slightly brighter lighting, and freedom to move around during the film. No previews or ads - just the feature. This month: family-friendly animated adventure.',
  'indoor',
  'Community Center Theater',
  '450 Center Street',
  'Bethlehem',
  'PA',
  '18017',
  40.6176,
  -75.3704,
  'theater@bethlehemcommunity.org',
  '(610) 555-0567',
  'https://bethlehemcommunity.org',
  ARRAY['Reduced sound volume', 'Brighter lighting than typical', 'Movement allowed', 'No sudden loud noises'],
  'Moderate',
  'Wheelchair accessible seating. Quiet room available if break needed. Free sensory bags with fidgets and noise-reducing headphones at entrance.',
  ARRAY['/placeholder.svg?height=400&width=600'],
  'events@bethlehemcommunity.org',
  'community',
  NOW() - INTERVAL '8 hours',
  NOW() - INTERVAL '8 hours',
  NOW() - INTERVAL '8 hours'
),
(
  gen_random_uuid(),
  'event',
  'pending',
  'Nature Walk & Bird Watching',
  'Gentle paced nature walk along accessible trails with optional bird watching. Group sizes limited to ensure peaceful experience. Binoculars provided. Event includes quiet observation periods and optional social time. Perfect for those who enjoy nature at a calm pace.',
  'outdoor',
  'Lehigh Parkway',
  '1400 Parkway Road',
  'Allentown',
  'PA',
  '18104',
  40.5887,
  -75.4557,
  'nature@lehighvalley.org',
  '(484) 555-0678',
  'https://lehighvalleynature.org',
  ARRAY['Outdoor activity', 'Small groups', 'Quiet observation time', 'Flexible pace'],
  'Low',
  'Paved accessible trail available. Benches along route for rest breaks. Communication cards available for non-verbal participants.',
  ARRAY['/placeholder.svg?height=400&width=600'],
  'guide@lehighvalley.org',
  'community',
  NOW() - INTERVAL '12 hours',
  NOW() - INTERVAL '12 hours',
  NOW() - INTERVAL '12 hours'
);

-- Add event dates for the event listings (set to 2 weeks from now)
UPDATE public.listings 
SET 
  event_date = CURRENT_DATE + INTERVAL '14 days',
  event_start_time = '10:00:00'::time,
  event_end_time = '12:00:00'::time
WHERE type = 'event' 
  AND status = 'pending'
  AND event_date IS NULL;
